export type Entry = {
	albumArt: string;
	song: string;
	sortSong: string;
	artist: string;
	sortArtist: string;
	genre: string;
	source: string;
	year: number;
	albumName: string;
	albumTrackIndex: number;
	id: number;
	hex: string;
	vocalsDifficulty: number | null;
	guitarDifficulty: number | null;
	drumDifficulty: number | null;
	bassDifficulty: number | null;
	keysDifficulty: number | null;
	proKeysDifficulty: number | null;
	proGuitarDifficulty: number | null;
	proBassDifficulty: number | null;
	bandDifficulty: number;
	vocalParts: number;
	multitracks: boolean;
	master: boolean;
	rating: number;
	duration: number;
	author: string;
	ogg: string;
};
